
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CARNET CARRERA CHAIN CORREO CREDITOS DESC DOLLAR DPI EDAD ELEMENT ELEMENTS EQUAL ESTADO FECHA HORA ID MATERIA NOMBRE NUMBER PASSWORD QC QO TYPE T_ITEMINICIO : QO ELEMENTS QC elementos QO DOLLAR ELEMENTS QCelementos : elementos elemento\n                 | elemento    \n                 elemento : QO ELEMENT tip_elem QC items  QO DOLLAR ELEMENT QCtip_elem : TYPE EQUAL CHAINitems : items item\n             | item\n             item : QO T_ITEM tipoItem EQUAL valorItem DOLLAR QC\n    valorItem : CHAIN\n                 | NUMBER\n                 tipoItem : CARNET\n                | DPI\n                | NOMBRE\n                | CARRERA\n                | PASSWORD\n                | CREDITOS\n                | EDAD\n                | CORREO\n                | DESC\n                | MATERIA\n                | FECHA\n                | HORA\n                | ESTADO\n                | ID\n                '
    
_lr_action_items = {'QO':([0,4,6,7,10,14,18,19,24,46,48,],[2,5,9,-3,-2,17,23,-7,-6,-4,-8,]),'$end':([1,21,],[0,-1,]),'ELEMENTS':([2,13,],[3,16,]),'QC':([3,11,16,20,42,47,],[4,14,21,-5,46,48,]),'ELEMENT':([5,9,40,],[8,8,42,]),'TYPE':([8,],[12,]),'DOLLAR':([9,23,43,44,45,],[13,40,47,-9,-10,]),'EQUAL':([12,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,],[15,41,-11,-12,-13,-14,-15,-16,-17,-18,-19,-20,-21,-22,-23,-24,]),'CHAIN':([15,41,],[20,44,]),'T_ITEM':([17,23,],[22,22,]),'CARNET':([22,],[26,]),'DPI':([22,],[27,]),'NOMBRE':([22,],[28,]),'CARRERA':([22,],[29,]),'PASSWORD':([22,],[30,]),'CREDITOS':([22,],[31,]),'EDAD':([22,],[32,]),'CORREO':([22,],[33,]),'DESC':([22,],[34,]),'MATERIA':([22,],[35,]),'FECHA':([22,],[36,]),'HORA':([22,],[37,]),'ESTADO':([22,],[38,]),'ID':([22,],[39,]),'NUMBER':([41,],[45,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'INICIO':([0,],[1,]),'elementos':([4,],[6,]),'elemento':([4,6,],[7,10,]),'tip_elem':([8,],[11,]),'items':([14,],[18,]),'item':([14,18,],[19,24,]),'tipoItem':([22,],[25,]),'valorItem':([41,],[43,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> INICIO","S'",1,None,None,None),
  ('INICIO -> QO ELEMENTS QC elementos QO DOLLAR ELEMENTS QC','INICIO',8,'p_statement_group','ASintactico.py',9),
  ('elementos -> elementos elemento','elementos',2,'p_elementos_group','ASintactico.py',13),
  ('elementos -> elemento','elementos',1,'p_elementos_group','ASintactico.py',14),
  ('elemento -> QO ELEMENT tip_elem QC items QO DOLLAR ELEMENT QC','elemento',9,'p_elemento','ASintactico.py',18),
  ('tip_elem -> TYPE EQUAL CHAIN','tip_elem',3,'p_tip_elem','ASintactico.py',24),
  ('items -> items item','items',2,'p_items_group','ASintactico.py',30),
  ('items -> item','items',1,'p_items_group','ASintactico.py',31),
  ('item -> QO T_ITEM tipoItem EQUAL valorItem DOLLAR QC','item',7,'p_item','ASintactico.py',37),
  ('valorItem -> CHAIN','valorItem',1,'p_valorItem','ASintactico.py',44),
  ('valorItem -> NUMBER','valorItem',1,'p_valorItem','ASintactico.py',45),
  ('tipoItem -> CARNET','tipoItem',1,'p_tipoItem','ASintactico.py',51),
  ('tipoItem -> DPI','tipoItem',1,'p_tipoItem','ASintactico.py',52),
  ('tipoItem -> NOMBRE','tipoItem',1,'p_tipoItem','ASintactico.py',53),
  ('tipoItem -> CARRERA','tipoItem',1,'p_tipoItem','ASintactico.py',54),
  ('tipoItem -> PASSWORD','tipoItem',1,'p_tipoItem','ASintactico.py',55),
  ('tipoItem -> CREDITOS','tipoItem',1,'p_tipoItem','ASintactico.py',56),
  ('tipoItem -> EDAD','tipoItem',1,'p_tipoItem','ASintactico.py',57),
  ('tipoItem -> CORREO','tipoItem',1,'p_tipoItem','ASintactico.py',58),
  ('tipoItem -> DESC','tipoItem',1,'p_tipoItem','ASintactico.py',59),
  ('tipoItem -> MATERIA','tipoItem',1,'p_tipoItem','ASintactico.py',60),
  ('tipoItem -> FECHA','tipoItem',1,'p_tipoItem','ASintactico.py',61),
  ('tipoItem -> HORA','tipoItem',1,'p_tipoItem','ASintactico.py',62),
  ('tipoItem -> ESTADO','tipoItem',1,'p_tipoItem','ASintactico.py',63),
  ('tipoItem -> ID','tipoItem',1,'p_tipoItem','ASintactico.py',64),
]
